name: isar_flutter_libs
description: Isar Core binaries for the Isar Database. Needs to be included for Flutter apps.
version: 3.1.4
repository: https://github.com/isar-community/isar
homepage: https://isar.dev
publish_to: https://isar-community.dev/

environment:
  sdk: "^3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 
    version: 3.1.4
    hosted: https://isar-community.dev/

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
